shared:
  accessToken: "pk.eyJ1Ijoic2VhbnBkb3lsZSIsImEiOiJja2YybWZkOTUxODdiMnNta2Y4cGp1dXVpIn0.CusYoNs-WHW3uTekCKyy_g"
  attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  animate: true
  id: "mapbox/streets-v11"
  maxZoom: 18
  templateUrl: "https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}"
  tileSize: 512
  zoomOffset: -1

test:
  animate: false
